### ISSUE TITLE
unwanted colon in the URL

### ISSUE THREAD

**Issue by azeunkn0wn** [g0rdan/publink#5]
It includes the colon.

This will open the url [json_serializable:](https://pub.dev/packages/json_serializable:) which is invalid.
![image](https://github.com/user-attachments/assets/8f68dc25-daba-4c92-9ffd-504564c9e76e)

**Comment by g0rdan** [comment]
@azeunkn0wn Thank you for reporting the issue!
Could I ask you what version of the extension is installed in your vscode and what version of vscode you have?

**Comment by azeunkn0wn** [comment]
publink v0.1.1
vscode v1.91.1

**Comment by g0rdan** [comment]
@azeunkn0wn I pushed an update (0.1.2), please have a look.

**Comment by azeunkn0wn** [comment]
It works perfectly now. thanks!

**Comment by azeunkn0wn** [comment]
It works perfectly now. Thanks!
